name: Test SSH and frpc Installation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Update package list
        run: sudo apt update
      
      - name: Purge SSH
        run: sudo apt purge -y ssh
      
      - name: Install SSH
        run: sudo apt install -y ssh
      
      - name: Start SSH service
        run: sudo /etc/init.d/ssh start
      
      - name: Download frpl.zip
        run: sudo wget 'https://github.com/fxlqwq/testgithubaction/releases/download/frp/frpl.zip'
      
      - name: Install unzip
        run: sudo apt install -y unzip
      
      - name: Unzip frpl.zip
        run: unzip -o frpl.zip
      
      - name: Make frpc executable
        run: sudo chmod +x ./frpc
      
      - name: Run frpc
        run: sudo ./frpc
