name: Configure Windows Server

on:
  push:
    branches:
      - main

jobs:
  configure:
    runs-on: windows-latest
    
    steps:
      - name: Set Terminal Server Configuration
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0

      - name: Create New Local User
        run: |
          New-LocalUser -Name 'fxlqwq' -Password (ConvertTo-SecureString 'Aa2980688' -AsPlainText -Force) -PasswordNeverExpires -Description 'New remote user'

      - name: Add New User to Administrators Group
        run: |
          Add-LocalGroupMember -Group 'Administrators' -Member 'fxlqwq'

      - name: Add New User to Remote Desktop Users Group
        run: |
          Add-LocalGroupMember -Group 'Remote Desktop Users' -Member 'fxlqwq'
          Invoke-WebRequest -Uri 'https://github.com/fxlqwq/testgithubaction/releases/download/frp/frp.zip' -OutFile '.\file.zip'
          Expand-Archive -Path '.\file.zip' -DestinationPath '.\frp'
          cd .\frp
          .\frpc.exe
